
lsi: false
safe: true
source: https://github.com/hexomicron/open-cs-course
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
